### ISSUE TITLE
Panic with interface value to nil

### ISSUE THREAD

**Issue by jlevesy** [upfluence/log#2]
### Issue description.

The following snippet makes the logger panic.

```
package main

import (
	"github.com/upfluence/log"
	"github.com/upfluence/log/sink/writer"
)

type dumbErr struct{}

func (d *dumbErr) Error() string {
	_ = *d

	return ""
}

func main() {
	var err *dumbErr

	l := log.NewLogger(log.WithSink(writer.NewStdoutSink(writer.NewDefaultFormatter("foo"))))
	l.WithError(err).Error("foo")
}

```

Output: 

```
go run experiment/main.go
[E 161120 11:37:30 main.go:20] foo [error: panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4aabe5]

goroutine 1 [running]:
main.(*dumbErr).Error(0x0, 0x55e0f0, 0x8)
	/home/jlevesy/Code/src/github.com/upfluence/log/experiment/main.go:11 +0x5
github.com/upfluence/log/sink/writer.(*formatter).formatErrs(0xc000024080, 0x4f2da0, 0xc00000e018, 0xc000010260, 0x1, 0x1)
	/home/jlevesy/Code/src/github.com/upfluence/log/sink/writer/formatter.go:96 +0xec
github.com/upfluence/log/sink/writer.(*formatter).Format(0xc000024080, 0x4f2da0, 0xc00000e018, 0x4f3980, 0xc00005c180, 0xa0736ace855, 0xc000072e20)
	/home/jlevesy/Code/src/github.com/upfluence/log/sink/writer/formatter.go:119 +0x335
github.com/upfluence/log/sink/writer.(*Sink).Log(0xc00006a1b0, 0x4f3980, 0xc00005c180, 0x4, 0x0)
	/home/jlevesy/Code/src/github.com/upfluence/log/sink/writer/sink.go:43 +0x82
github.com/upfluence/log.(*logger).Logf(0xc0000660a0, 0x4, 0x0, 0x0, 0xc000010240, 0x1, 0x1)
	/home/jlevesy/Code/src/github.com/upfluence/log/logger.go:158 +0xcc
github.com/upfluence/log.(*logger).Errorf(...)
	/home/jlevesy/Code/src/github.com/upfluence/log/logger.go:190
github.com/upfluence/log.(*logger).Error(0xc0000660a0, 0xc000010240, 0x1, 0x1)
	/home/jlevesy/Code/src/github.com/upfluence/log/logger.go:170 +0x5a
main.main()
	/home/jlevesy/Code/src/github.com/upfluence/log/experiment/main.go:20 +0x251
exit status 2
```

The problem is that `WithError` does not handle properly interface values to nil pointers.

**Comment by AlexisMontagne** [comment]
It does handle the  `nil` typed `error` ( the scalar type) not the nil pointer towards a random type. (cf. here https://github.com/upfluence/log/blob/master/logger.go#L142 ). 

In your example you do not pass a nil value of the error interface cf. https://play.golang.org/p/7DlUyGdH0Hs

How would you fix it? The only way to fix it that i can see is to apply reflection on the value and i dont think it is a great idea here, it might slow down the logger quite a bit (some log line could be in a hot path).

**Comment by jlevesy** [comment]
> How would you fix it? The only way to fix it that i can see is to apply reflection on the value and i dont think it is a great idea here, it might slow down the logger quite a bit

Yeah I did not made any fix because the only option I had in mind is indeed to use reflection so I wanted your opinion on this first.
I was suggesting internally to :eyes: at https://github.com/modern-go/reflect2, which is way faster than stdlib reflect and could be a good fit in our case.

We could try to bench its impact, WDYT?

**Comment by AlexisMontagne** [comment]
As it stands this repo only rely on the stdlib, no 3rd party dependencies. And this is something i would like to keep this way.

Do you have any actual example where it happened in the code? I do think if you provoke this use case (having a nil typed error) you might also mess up all the `if err != nil` along the call path.

**Comment by jlevesy** [comment]
Closing, won't fix.
